# Los virus y el color de las plantas{#ID1}

## La primera burbuja especulativa y el virus del mosaico del tulipan. 

<https://www.facebook.com/BioViral/posts/166521528808498> 

En épocas de pandemia viral se hacen más populares frases negativas en torno a los virus tales como la ya famosa cita del premio nobel de medicina Peter Medawar:

[Un virus es] “una mala noticia envuelta en una cubierta de proteína”.


Quizá la popularidad de este tipo de creencias nos impide explorar estos seres vivos tan incomprendidos; de hecho, no resulta extraño que la mayoría aplastante de investigaciones en virología sean del índole médico. Quizá si nos enfocamos primero en entender y no en cómo eliminar, podríamos prevenir de una mejor manera las futuras crisis sanitarias que los virólogos y epidemiólogos YA anticipan.

Para ejemplificar la otra cara de la virología, un aspecto de interés de la virología básica — y de poca relevancia para la virología médica —, se encuentra el virus del mosaico del tulipán. Este es uno de los encargados de embellecer aún más el panorama de colores florales de algunas plantas en primavera, esto al incidir en la inhibición de la maquinaria regulatoria mediada por pequeños RNAs, que a su vez inhibe la producción de ciertas enzimas involucradas en la biosíntesis de flavonoides, los pigmentos vegetales que otorgan las coloraciones con tonos amarillas, verdes, púrpuras, azules y rojizas. 

En lo que respecta a colores florales, "menos por menos es más": durante la infección a la planta huésped, el virus inhibe una de las maquinarias que despliega la planta para su control, los pequeños ARNs de interferencia (small interference RNAs o sRNAi), que a su vez inhibe la expresión de los genes blancos, por complementariedad con el pequeño ARN. Dentro de la lista de genes blancos se encuentran aquellos que  promueven la biosíntesis de los pigmentos previamente mencionados. La infección del virus altera esta inhibición, permitiendo expresar en aquellas células infectadas los pigmentos que otorgan la coloración; generando patrones contrastantes entre células infectadas y no infectadas (Figura 3).

Este efecto visual, hizo que el virus del mosaico del tulipán, desatara no una pandemia, pero sí la admiración y la codicia humana que desencadenó la primera crisis económica del viejo mundo: la Tulipomanía del 1637; ejemplificando cómo los virus hacen parte de la biosfera entera, capaz de alterar interacciones ecológicas antiguas o novedosas, y de paso, el sistema económico humano.

## Infecciones virales a simple vista

<https://www.facebook.com/permalink.php?story_fbid=116167563441400&id=107088044349352>