# Autores {-}

* **Aimer G. Díaz**: MSc. Bioinformático y Biólogo de la Universidad Nacional de Colombia. Fundador del blog de divulgación de virología biológica o no-médica "Bio-Virología". Co-fundador, escritor y editor del blog de divulgación científica [Biología Teórica para T@dos](https://bioteorica.wixsite.com/bioteorica/blog) (En [Facebook](https://www.facebook.com/BioTeoricaParaTodos/)), además de escribir para [Biología Molecular México](http://www.biologiamolecularmexico.com/) (En [Facebook](https://www.facebook.com/biologiamolecularmexico/)). Actualmente estudiante de doctorado y miembro investigador del Centro para el estudio de la evolución en acción BEACON. Los ejes temáticos en los que se concentra su investigación y divulgación científica son Virología, Bioinformática, Biología Evolutiva y Filosofía de la Biología, pese a la diversidad de áreas todas estas convergen alrededor de la Virología evolutiva computacional. 

* **Víctor Parra Avellaneda**: Estudia la licenciatura en Biología en el Centro Universitario de Ciencias Biológicas y Agropecuarias de la Universidad de Guadalajara. Fundador del blog de divulgación científica Mimivirus [(en Facebook)](https://www.facebook.com/Mimivirus-100736401569015), enfocado en virología. Los ejes temáticos abordados en su divulgación científica son la virología, ingeniería genética, microbiología y biología sintética. Por otra parte, también se desempeña en el ámbito literario, específicamente en la ciencia ficción. Es autor de la novela satírica El intrigante caso de Locostein, (Editorial Dreamers, 2019), ha publicado sus relatos en revistas literarias como Axxón, Marabunta, Penumbria, Sci:fdI (revista de la Universidad Complutense de Madrid), Almiar; en inglés en las revistas The Temz Review, Nymphs y Teleport Magazine; y en francés en Dumas de demain. Fue becario del PECDA Nayarit 2018-2019 en la categoría de cuento. Es fundador y co-editor de la revista literaria de ficción especulativa Primero Sueño.

* **Juan Corao**:  Biólogo con especialidad en biología celular de la Universidad de los Andes, Mérida, Venezuela. Como profesional siempre ha buscado un enfoque multidisciplinario e integrativo dirigido a la conservación de la biodiversidad y agro-biodiversidad, realizando múltiples trabajos de asesoramiento ambiental en manejo de fuentes y nacientes de agua en distintos ecosistemas y países, así como en el diseño de planes de manejo ambiental para múltiples fines. Ha trabajado como asesor para la empresa privada, ONU mujeres Ecuador,  Instituto Nacional de Investigaciones Agrícolas INIA Venezuela. También maneja una empresa de generación de semillas de hongos comestibles y distintos bioinsumos para el sector agrícola. Actualmente es profesor de genética en el departamento de Biología, Facultad de Ciencias, Universidad de los Andes, Mérida Venezuela. Sus intereses  académicos tienen que ver con la metagenómica aplicada a la conservación y al monitoreo del cambio climático y su impacto en la biodiversidad. Para el 2022 comienza un doctorado en ecología tropical en el Instituto de Ciencias Ambientales y Ecológicas ICAE, ULA. 


* **Roberto Nájera**: Autodidacta en Biología molecular, fisiología, farmacología, cinética enzimática y biología de sistema. Fundador del blog [Quantum Rabbit](https://www.facebook.com/Medicina88) de divulgación científica y del canal homonimo de animaciones científicas de procesos fisiológicos y bioquímicos en [YouTube](https://www.youtube.com/channel/UC21O3WpoUEXuu6ZmvkFHOCA).  Sus intereses radican en especial en la compresión del Envejecimiento, cáncer, Bio-ingeniería de proteínas y Modelación matemática del metabolismo celular.


* **Natalia Alejandra Chaparro**:  Magíster en Filosofía de la Universidad Nacional de Colombia con licenciatura en español y filología clásica. Bajo el cobijo del amor a la sabiduría, Natalia busca conocer y reflexionar la vida con todas sus particularidades.